### - - - - - - - - - - - - - - - - - - COMMENTS - - - - - - - - -- - - - - - - - -
### post new comment
POST http://localhost:5000/api/comments/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJkZDg0NjUzM2U5MGQwNDZmZGYyYSIsImlhdCI6MTYxOTUyOTE2OCwiZXhwIjoxNjE5NjE1NTY4fQ.U8gEM6BLqpIqBu47HJkrZVtKRloYkmvUWeYpVHT6KQc

{
    "postId": "60817951caa28f3384f83eb9",
    "content": "123"
}

### - - - - - - - - - - - - - - - - - - PM - - - - - - - - -- - - - - - - - -
### get all pm
GET http://localhost:5000/api/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJkZDg0NjUzM2U5MGQwNDZmZGYyYSIsImlhdCI6MTYxOTUyOTE2OCwiZXhwIjoxNjE5NjE1NTY4fQ.U8gEM6BLqpIqBu47HJkrZVtKRloYkmvUWeYpVHT6KQc

### post new pm
POST http://localhost:5000/api/private HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJkZDhjNjUzM2U5MGQwNDZmZGYyYiIsImlhdCI6MTYxOTI3MTgxOCwiZXhwIjoxNjE5MzU4MjE4fQ.QRSCJm4F3DHuTz6e_md0XbU0_YQyZiVf6aHNm9cqAJU

{
    "friendId": "6082dd8c6533e90d046fdf2b",
    "content": "123"
}

### delete pm
DELETE http://localhost:5000/api/private HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJkZDg0NjUzM2U5MGQwNDZmZGYyYSIsImlhdCI6MTYxOTUzNDMzNCwiZXhwIjoxNjE5NjIwNzM0fQ.1Xc0xpaxSCktx619fHp37bHStvt8Op2823gVuhTuWCg

{
    "friendId": "6082dd8c6533e90d046fdf2b"
}

### get pm by userId
// TODO
GET http://localhost:5000/api/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJkZDg0NjUzM2U5MGQwNDZmZGYyYSIsImlhdCI6MTYxOTUyOTE2OCwiZXhwIjoxNjE5NjE1NTY4fQ.U8gEM6BLqpIqBu47HJkrZVtKRloYkmvUWeYpVHT6KQc